### ISSUE TITLE
Goat Horn "Instrument" variant not working

### ISSUE THREAD

**Issue by Alcmae0n** [Estecka/mc-Enchants-CIT#20]
Hello! I'm currently working on upgrading a texture pack I used to use (original creator credits are in the pack's mcmeta) and have set up an instrument module with filename "goat_horn.json" :

```
{
	"type": "instrument",
	"modelPrefix": "item/goat_horn_"
}
```
With a model file name "goat_horn_admire.json" :

```
{
	"parent": "item/generated",
	"textures": {
		"layer0": "item/goat_horn_admire"
	}
}
```
However, the goat horn texture does not seem to be changing despite the goat horn being the correct instrument.

![goat_horn_issue](https://github.com/user-attachments/assets/e7c1d640-6a11-4d2d-8939-1132a5f643a5)

Attached is the WIP resource pack for the 'Admire' goat horn only. 
[goat-horns-variants.zip](https://github.com/user-attachments/files/18176095/goat-horns-variants.zip)

Please let me know if there is something wrong with the code! Also once Admire goat horn is working, I plan to apply the same to the rest of the goat horns.

**Comment by Estecka** [comment]
- In this zip file, your model prefix is actually set to `"item/goat_horn_/"`, with a trailing slash.
 - Your module was in the wrong directory, `variant-cit` (singular) instead of `variants-cit` (plural).
 - The actual identifier for that instrument is `admire_goat_horn`. For some reason all vanilla instruments are suffixed with `_goat_horn`, so you'll need to add this to your filenames _in addition to_ the module's prefix. I don't want to automatically strip that suffix off in case modded instruments don't follow that naming convention, but I'll add a mention of this oddity in the wiki. In my personal opinion, using `item/goat_horn/` as a prefix would make the filenames look more elegant here.

**Comment by Alcmae0n** [comment]
Thanks for the help! I'm pretty new to creating CIT resource packs so a bit unsure how to accomplish what you mean in adding the `_goat_horn` suffix to the module's prefix. Could you give me an example of this please?

**Comment by Estecka** [comment]
Modules don't support suffixes, so your module would be practically unchanged.

What I mean is just renaming your texture and model files.
So for example `goat_horn_admire_goat_horn.json` or `goat_horn/admire_goat_horn.json` depending on your prefix.

**Comment by Alcmae0n** [comment]
Have I got this correct? Apologies for the long back and forth
[goat-horns-variants-update.zip](https://github.com/user-attachments/files/18240463/goat-horns-variants-update.zip)

**Comment by Alcmae0n** [comment]
![Goat-Horns-Success](https://github.com/user-attachments/assets/7cca3189-a884-42d9-aa87-60ebc695b463)

I got the pack to work with Admire and added the rest of the other goat horn variants also. Thank you very much for the help! :D
