### ISSUE TITLE
CITs based on custom name.

### ISSUE THREAD

**Issue by lukasabbe** [Estecka/mc-Enchants-CIT#4]
If you want only to apply a modelPrefix if the item:s name is the one you want is there a possibility for that now? Or do I need to add that my self?

**Comment by Estecka** [comment]
I don't think I understand the question, can you please elaborate ?

**Comment by lukasabbe** [comment]
Sorry if I am not clear. Haven't used cit so much. But in CIT there is a type just called item. With that you can specify one item and there you can have a property for the items nbt values. And there you can check its name. 

Hope you understand. 
Haha sorry if I was unclear

**Comment by Estecka** [comment]
Oh, you meant the item's custom name. It's currently not possible, but it's something I was hoping to add.

The issue holding it back is that I'm not sure how you would create the association between names and models. I've had two different ideas on how to implement this, but both come with considerable drawbacks:

My first idea was to define the names and their associated variant IDs in the `parameters` block of the module config. The downside is that it would only work for a single resource pack; if other packs tried to expand upon that list, they'd end up overwritting each other's config instead.

The other idea was to directly parse the item's name as the variant identifier. Its is my favourite for now, it's more in line with how the mod is intended to work, because you wouldn't need to define the names anywhere. The downside is that it would put harsh restrictions on what names would be valid options, which would be restricted to the same character set as namespaced identifiers.

**Comment by lukasabbe** [comment]
I understand, ye definitely think the second one is better.

**Comment by Estecka** [comment]
I don't expect being able to do anything cleaner without major changes, but I guess it wouldn't hurt to have a partial solution for now. The two ideas aren't fundamentally incompatible either, so I'll get something done that can work with both.
